services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "leesf003/portfolio-web"
    volumes:
      - /app/node_modules
      - static:/app/.next/static
      - images:/app/public/img
    ports:
      - "3000:3000"
    env_file: ./.env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 1m
    #   start_interval: 5s

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
      tags:
        - "leesf003/portfolio-nginx"
    # depends_on:
    #   web:
    #     condition: service_healthy
    volumes:
      - static:/var/www/portfolio/_next/static
      - images:/var/www/portfolio/img
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=portfolio-nginx.com
      - NGINX_PORT=80

volumes:
  static:

  images:
