services:
  web:
    image: leesf003/portfolio-web
    container_name: web
    volumes:
      - /app/node_modules
      - static:/app/.next/static
      - images:/app/public/img
    ports:
      - '3000:3000'
    env_file: ./.env

  nginx:
    image: leesf003/portfolio-nginx
    container_name: nginx
    volumes:
      - static:/var/www/portfolio/_next/static
      - images:/var/www/portfolio/img
      - acme:/var/www/acme
      - /etc/letsencrypt:/var/www/cert
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NGINX_HOST=portfolio-nginx.com
      - NGINX_PORT=80

  certbot:
    image: leesf003/cert-renewal-cron
    container_name: certbot-renew-cron
    depends_on:
      - nginx
    volumes:
      - acme:/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  static:

  images:

  acme:

  # cert:
  #   external: true
