- name: Update sshd config
  hosts: azure
  become: true
  tasks:
    - name: Change ssh PasswordAuthentication to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication*"
        line: "PasswordAuthentication no"
        state: present

    - name: Change ssh PermitRootLogin to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin*"
        line: "PermitRootLogin no"
        state: present

    - name: Reload sshd
      systemd_service:
        name: sshd
        state: reloaded
