services:
  prometheus:
    image: leesf003/portfolio-prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - prometheus:/prometheus
    networks:
      - deployment

  grafana:
    image: leesf003/portfolio-grafana
    container_name: grafana
    ports:
      - '3001:3000'
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - deployment

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.0
    container_name: nginx-prometheus-exporter
    ports:
      - '9113:9113'
    command: |
      --nginx.scrape-uri=http://nginx:80/stub_status
    networks:
      - deployment

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - deployment

  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    expose:
      - 9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - deployment

volumes:
  prometheus:
    external: true

  grafana:
    external: true

networks:
  deployment:
    name: deployment
    external: true
