name: Build and push docker image
run-name: Building docker image of web, nginx and certbot
on:
  push:
    branches:
      - main

jobs:
  Build_Push_Docker_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push web image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: dockerfile
          tags: leesf003/portfolio-web:latest

      - name: Build and push nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: nginx.dockerfile
          tags: leesf003/portfolio-nginx:latest

      - name: Build and push certbot image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: certbot.dockerfile
          tags: leesf003/cert-renewal-cron:latest
