name: Deploy container to VM
run-name: Deploying container to Azure VM
on:
  workflow_run:
    workflows:
      - Build and push docker image
    types:
      - completed

jobs:
  deploy_containers:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/leesf_az_key_pair.pem
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/leesf_az_key_pair.pem
          chmod 600 ~/.ssh/leesf_az_key_pair.pem

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: leesf
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i deployment/inventory.yaml deployment/playbooks/deploy.yaml
